
spring:
  application:
    name: jpa-data
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb_jpa
    username: root
    password: passer
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8000